TITLE="Beej's Guide to Interprocess Communication"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v1.5.2, Copyright © January 24, 2026"

GUIDE_ID=bgipc
BGBSPD_BUILD_DIR?=../../bgbspd

WEB_IMAGES=$(wildcard *.svg)

include $(BGBSPD_BUILD_DIR)/source.make

