TITLE="Beej's Guide to Interprocess Communication"
SUBTITLE=""
AUTHOR='Brian “Beej Jorgensen” Hall'
VERSION_DATE="v1.1.4, Copyright © February 4, 2023"

GUIDE_ID=bgipc
BGBSPD_BUILD_DIR?=../../bgbspd

WEB_IMAGES=$(wildcard *.svg)

include $(BGBSPD_BUILD_DIR)/source.make

